---

- hosts: all
  become: true
  tasks:

  - name:
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: install apache2
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_server
  become: true
  pre_tasks:

  - name: install maria
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
